export const dbTables = {
  SPORT_TABLE: 'SPORT_TABLE',
  BETFAIR_EVENT_TABLE: 'BETFAIR_EVENT_TABLE',
  BETFAIR_MARKET_TABLE: 'BETFAIR_MARKET_TABLE',
  BETFAIR_RUNNER_TABLE: 'BETFAIR_RUNNER_TABLE',
};
